version = 1

test_patterns = ["src/test/**"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs", "jest", "mongo"]
module_system = "es-modules"
dialect = "typescript"
skip_doc_coverage = ["class-expression", "method-definition"]

[[transformers]]
name = "prettier"
enabled = true
